- name: install and run http
  hosts: localhost
  become: yes
  tasks:
  - name: install the http
    ansible.builtin.dnf:
      name: http
      state: latest
  - name: start the http
    ansible.builtin.service:
      name: httpd
      state: started 
      enabled: yes

