- name: install and run nginx
  hosts: localhost
  become: yes
  tasks:
  - name: install the ngnix
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started 
      enabled: yes

