- name: variables from files
  #hosts: localhost
  vars_files:
  vars_prompt:
  - name: username
    prompt: pls enetr usernmae
    private: false
  - name: password
    prompt: pls enter password
    private: false
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: "hi username: {{username}}, passwod is: {{password}}"
