- name: printing variables from inventory
  hosts: localhost

    #wishes: "good morning from variable file"
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: "hi, we are learning {{course}} from trainer {{trainer}} duration is {{duration}}."