- name: variables from inventory
  hosts: localhost  
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: "hi we are learning from trainer {{trainer}} duration is {{duration}}"