- nmae: variables preference
  hosts: localhost
  vars:
    wishes: "good morning from play variables"
    vars_files:
    - vars.yaml
    vars_prompt:
    - name: wishes
      prompt: pls enetr wishes 
      private: false  
  tasks:
  - name: for checking varaibles preference
    vars:
      wishes: "good morning from task variables"
    ansilble.builtin.debug:
      msg: "hello , good {{wishes}}"  



#first prefernce goes to args
#second preference goes to task level
#third preference goes to variable
#fourth preference goes to prompt  
#fifth preference goes to play 
#sixth preference goes to inventory file     