- name: conditions
  hosts: localhost
  become: yes
  tasks: 
  - name: check user exists or not
    ansilble.builtin.command: id expense

  - name: say hello
    ansilble.builtin.debug:
      msg:  "hello"

  #   register: user
  #   ignore_errors: true
  # - name: print user information
  #   ansilble.builtin.debug:
  #     msg: "user info: {{user}}"  
  # - name: create user
  #   ansilble.builtin.command: useradd expense
  #   when: user.rc != 0 
  # - name: say hello
  #   ansilble.builtin.debug:
  #     msg: "hello"