- name: default value
  hosts: localhost
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg:  "heelo {{couse | ('Ansible') }}" #providing default value when variable not declared

- name: upper case
  hosts: localhost
  vars:
    geerting:  "hello good morning"
  tasks:
  - name: covert into upper case
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"     


- name: lower case
  hosts: localhost
  vars:
    geerting:  "hello good morning"
  tasks:
  - name: covert into lower case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"     


- name: remove duplicates
  hosts: localhost
  numbers: [1, 2, 3, 3, 4, 4, 5]  
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"       



- name: print min and max
  hosts: localhost
  vars: 
    ages: [25, 35, 40, 60]     
  tasks:
  - name: print min and max
    ansible.builtin.debug:
     msg: "min age is: {{ ages | min }}, max age is: {{ ages | max }}"

- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict:
      course: ansible
      trainer: siva 
      duration: 120hrs
  tasks:
  - name: before conert dictionary into list / items  
    ansible.builtin.debug:
      msg: "before convert: {{ my_dict }}"       
  - name: after conert dictionary into list / items  
    ansible.builtin.debug:
      msg: "after convert: {{ my_dict | dict2items }}"      

